version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  node:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./:/code
volumes:
  mongodb:
